AWSTemplateFormatVersion: 2010-09-09
Description: |
  İlk proje
Parameters:
  KeyPair:
    Description: Key Pair Seç
    Type: AWS::EC2::KeyPair::KeyName
  ParameterName:
    Description: VPC seç
    Type: AWS::EC2::VPC::Id
Resources:
  EC2SecGrup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group  # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        Key: Name
        Value: EC2SecGrup
  YasinEC2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      ImageId: ami-09d3b3274b6c5d4aa
      InstanceType: t2.micro
      Monitoring: false
      SecurityGroupIds: !Ref EC2SecGrup
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install python3 -y
        pip3 install flask
        cd /home/ec2-user
        wget https://raw.githubusercontent.com/Kaya-Y/friends-projects/main/flask-01-02-hello-world-app-Jinja-Template/
        cd flask-01-02-hello-world-app-Jinja-Template/flask-01-hello-world-app/
        python3 hello-world-app.py
      Tags:
        - Key: Name
          Value: YasinEC2
Outputs: 
  WebsiteURL:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt YasinEC2.PublicDnsName